//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public bool Arata { get; set; }
        public decimal Pret { get; set; }
        public decimal PretCuDiscount { get; set; }
        public int Cantitate { get; set; }
        public string Descriere { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime DataCreare { get; set; }
        public int CategorieId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItem> SaleItems { get; set; }
        public virtual Category Category { get; set; }
    }
}
